Iceman Iteration 2 on project recipes
DanSam5K/class-work pull request #13
Opened 2022-07-26 18:06 UTC by Kadunapikin

Create a new recipe folder within project-recipes,
Create a new chickenpaprikash.html file inside the recipe folder,
Add a relative link to chickenpaprikash page on index.html page.

2022-07-26 20:25 UTC, DanSam5K requested changes
## Hi @Kadunapikin, ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![ ](https://user-images.githubusercontent.com/64173189/128109485-382fcc99-cf3c-4534-a70a-51351dfd9b39.gif)

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly check the [recipe link here](https://www.allrecipes.com/) to see example of the recipe
- [ ] Please I think you are suppose to complete the project from step 1 to 4 as mention here
[Odin Recipe project](https://www.theodinproject.com/lessons/foundations-recipes). what do you think?
- [ ] How about including some tags like the list of recipe and steps and procedure as mention in the project?

 - Cheers and happy coding 👏

2022-07-30 10:09 UTC, DanSam5K approved these changes
## Hi @Kadunapikin , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-07-31 12:40 UTC, phildeone approved these changes
Good job 👌👍

2022-08-04 06:43 UTC, zizoh approved these changes

2022-08-04 13:53 UTC, merged